export const USER_SIGNUP = 'USER_SIGNUP';
export const FETCH_INIT_SIGNUP = 'FETCH_INIT_SIGNUP';
export const FETCH_SUCCESS_SIGNUP = 'FETCH_SUCCESS_SIGNUP';
export const FETCH_FAILURE_SIGNUP = 'FETCH_FAILURE_SIGNUP';
export const CLEAR_STATE_SIGNUP = 'CLEAR_STATE_SIGNUP';
