export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const FETCH_INIT_AUTHENTICATION = 'FETCH_INIT_AUTHENTICATION';
export const FETCH_SUCCESS_AUTHENTICATION = 'FETCH_SUCCESS_AUTHENTICATION';
export const FETCH_FAILURE_AUTHENTICATION = 'FETCH_FAILURE_AUTHENTICATION';
export const CHECK_TOKEN = 'CHECK_TOKEN';
